### PR TITLE
pass exception information to javascript for possible handling

### LINKED ISSUE #291: for javascript calling python, return promises that support catch
The ability to call in to python works great, but I find myself having to put try/except wrappers around everything and then the return codes also have to return status and exception information.

Perhaps an API where a true promise was returned (vs. passing in a callback) so that the result and catch can be handled depending on if an error occurred.

### PR DESCRIPTION
**Pull request by Kevinrp01**
Closes #291 - save a resolve and reject pointer for promises returned by calling python functions

### CODE REVIEW

**Comment by Kevinrp01** [comment]
Added some examples as well, let me know if you want the readme updated...for now I left that out due the try/catch being a tad more complex.

**Comment by Kevinrp01** [comment]
Anything else needed for this pull request to be considered?

**Comment by samuelhwilliams** [comment]
Hi @Kevinrp01 - thanks for the PR. It looks good to me but I'd be keen to get @ChrisKnott's opinion.

**Comment by ChrisKnott** [comment]
Yes, I think this is fine. It is technically a breaking change but I don't feel like we ever guaranteed behaviour in the case of exceptions.

It makes particular sense for JS heavy apps that make occasional calls to py.

Is there an easy way to do the reverse? Raise uncaught js exceptions back to python?

**Comment by Kevinrp01** [comment]
Good point, I'll see about adding that as well

**Comment by Kevinrp01** [comment]
I am not familiar enough with python equivalent of promises and couldn't figure out a way for an exception to be generated such that the user function could handle it...so instead, I just extended the callback flow and so users can provide a 2nd callback function that will be called if an error occurs.

failure callback takes error message (simple string), and error stack (full javascript failure stack)

**Comment by Kevinrp01** [comment]
@ChrisKnott just checking in on this again in case you have any more input or changes requested

**Comment by ChrisKnott** [comment]
Sorry I didn't get a chance yet, I reckon just ship this half of it and if I ever get time I can look into adding the reverse for Python side.

**Comment by samuelhwilliams** [comment]
Thanks for the contribution @Kevinrp01 👍

**Pull request merged**
